# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "gusztavvargadr/w1809ssc"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    # stuff gets done here

    Set-ExecutionPolicy Bypass -Scope Process -Force
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    choco install git -y
    choco install poshgit -y
    choco install vagrant -y
    choco install awscli -y
    choco install awspowershell -y
    choco install ruby -y
    Install-Module Carbon -force -allowclobber
    Install-Module Pester -force -SkipPublisherCheck
    Install-Module PSScriptAnalyzer -force

    refreshenv

    mkdir c:\\source
    mkdir c:\\source\\repos
    set-location c:\\source\\repos
    New-Alias git "C:\\Program Files\\git\\cmd\\git.exe"


    # sysprep the thing
    sysprep.exe /generalize /oobe /shutdown /quiet
  SHELL
end
