# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "gusztavvargadr/windows-10"

  config.vm.provider "virtualbox" do |v|
    v.name = "Windows 10 Dev Box"
    v.memory = 4098
    v.customize ["modifyvm", :id, "--vram", "64"]
  end


  config.vm.provision "shell", inline: <<-SHELL
    # stuff gets done here

    Set-ExecutionPolicy Bypass -Scope Process -Force
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

@(
    "git",
    "poshgit",
    "googlechrome",
    "visualstudiocode",
    "VisualStudio2017Professional",
    "NotepadPlusPlus",
    "pscx",
    "carbon",
    "putty",
    "awstools.powershell",
    "nodejs",
    "sysinternals",
    "haroopad",
    "dotnetcore",
    "awscli",
    "vagrant",
    "nuget.commandline",
    "rubymine",
    "ruby"
) | % { cinst $_ -y }

    choco install visualstudiocode -y

    Install-Module Pester -force -SkipPublisherCheck
    Install-Module PSScriptAnalyzer -force

    refreshenv

    mkdir c:\\source
    mkdir c:\\source\\repos
    set-location c:\\source\\repos
    New-Alias git "C:\\Program Files\\git\\cmd\\git.exe"

    @(
    "aws-scripting-guy.cform",
    "eamodio.gitlens",
    "Ionide.Ionide-fsharp",
    "Ionide-FAKE",
    "Ionide-Paket",
    "ms-vscode.csharp",
    "ms-vscode.PowerShell",
    "PeterJausovec.vscode-docker",
    "ms-kubernetes-tools.vscode-kubernetes-tools",
    "ms-python.python",
    "redhat.vscode-yaml",
    "sdras.night-owl",
    "ms-azuretools.vscode-azurefunctions"
) | % { code --install-extension $_ }



  SHELL
end
