version: 2.1
jobs:
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: "Run Tests"
          shell: bash
          command: |
            echo "oh hey, tests will go here when they're ready"
  pack:
    docker:
      - image: ubuntu:18.04
    environment:
      PACKAGE_VERSION: 0.0.<< pipeline.number >>
    steps:
      - octo/install-tools
      - checkout
      - octo/pack:
          id: "VagrantCalendarbox"
          version: $PACKAGE_VERSION
          base_path: "./CalendarBox/"
          out_folder: "package"
      - persist_to_workspace:
          root: package
          paths:
            - ./
  push:
    docker:
      - image: ubuntu:18.04
    environment:
      PACKAGE_VERSION: 0.0.<< pipeline.number >>
    steps:
      - octo/install-tools
      - attach_workspace:
          at: pack
      - octo/push:
          package: "./package/VagrantCalendarbox.${PACKAGE_VERSION}.zip"
          server: OCTOPUS_CLI_SERVER
          api_key: OCTOPUS_CLI_API_KEY
          debug: true
      - octo/build-information:
          package_id: "VagrantCalendarbox"
          version: ${PACKAGE_VERSION}
          server: OCTOPUS_CLI_SERVER
          api_key: OCTOPUS_CLI_API_KEY
          debug: true
  create-release:
    docker:
      - image: ubuntu:18.04
    environment:
      PACKAGE_VERSION: 0.0.<< pipeline.number >>
    steps:
      - octo/install-tools
      - octo/create-release:
          project: "Vagrant Calendarbox"
          server: OCTOPUS_CLI_SERVER
          api_key: OCTOPUS_CLI_API_KEY
          release_number: $PACKAGE_VERSION
workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
      - pack:
          requires:
            - test
          context: Octopus
          filters:
            branches:
              only: /main/
      - push:
          requires:
            - test
            - pack
          context: Octopus
          filters:
            branches:
              only: /main/
      - create-release:
          requires:
            - test
            - pack
            - push
          context: Octopus
          filters:
            branches:
              only: /main/
orbs:
  windows-tools: circleci/windows@2.2.0
  octo: stopthatastronaut/octopus-cli@dev:nosudo2
