# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "hyperv" do |hv|
    hv.memory = 2048 
    hv.vmname = "Ubuntu-NFS"
    hv.cpus = 2
  end 

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    # Download the Microsoft repository GPG keys
    wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb

    # Register the Microsoft repository GPG keys
    dpkg -i packages-microsoft-prod.deb

    apt-get update
    apt-get install -y nfs-kernel-server
    apt-get install -y powershell
  SHELL
end
